<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQPTdlY7\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQPTdlY7/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQPTdlY7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQPTdlY7\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerQPTdlY7\srcApp_KernelProdContainer([
    'container.build_hash' => 'QPTdlY7',
    'container.build_id' => '388c8cd7',
    'container.build_time' => 1627078858,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQPTdlY7');
