<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGLGPAu7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGLGPAu7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGLGPAu7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGLGPAu7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGLGPAu7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GLGPAu7',
    'container.build_id' => '1e29b915',
    'container.build_time' => 1627599385,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGLGPAu7');
