<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \App\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'moreInformations', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'isBestSeller', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'isNewArrival', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'isFeatured', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'isSpecialOffer', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'category', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'relatedProducts', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'reviewsProducts', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'quantity', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'tags', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'slug'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'moreInformations', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'isBestSeller', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'isNewArrival', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'isFeatured', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'isSpecialOffer', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'category', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'relatedProducts', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'reviewsProducts', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'quantity', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'tags', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'slug'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoreInformations(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoreInformations', []);

        return parent::getMoreInformations();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoreInformations(?string $moreInformations): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoreInformations', [$moreInformations]);

        return parent::setMoreInformations($moreInformations);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice(float $price): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsBestSeller(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsBestSeller', []);

        return parent::getIsBestSeller();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsBestSeller(?bool $isBestSeller): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsBestSeller', [$isBestSeller]);

        return parent::setIsBestSeller($isBestSeller);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsNewArrival(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsNewArrival', []);

        return parent::getIsNewArrival();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsNewArrival(?bool $isNewArrival): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsNewArrival', [$isNewArrival]);

        return parent::setIsNewArrival($isNewArrival);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsFeatured(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsFeatured', []);

        return parent::getIsFeatured();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsFeatured(?bool $isFeatured): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsFeatured', [$isFeatured]);

        return parent::setIsFeatured($isFeatured);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsSpecialOffer(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsSpecialOffer', []);

        return parent::getIsSpecialOffer();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsSpecialOffer(?bool $isSpecialOffer): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsSpecialOffer', [$isSpecialOffer]);

        return parent::setIsSpecialOffer($isSpecialOffer);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(string $image): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function addCategory(\App\Entity\Categories $category): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCategory', [$category]);

        return parent::addCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCategory(\App\Entity\Categories $category): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCategory', [$category]);

        return parent::removeCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedProducts(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedProducts', []);

        return parent::getRelatedProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedProduct(\App\Entity\RelatedProduct $relatedProduct): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedProduct', [$relatedProduct]);

        return parent::addRelatedProduct($relatedProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedProduct(\App\Entity\RelatedProduct $relatedProduct): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedProduct', [$relatedProduct]);

        return parent::removeRelatedProduct($relatedProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getReviewsProducts(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReviewsProducts', []);

        return parent::getReviewsProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function addReviewsProduct(\App\Entity\ReviewsProduct $reviewsProduct): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReviewsProduct', [$reviewsProduct]);

        return parent::addReviewsProduct($reviewsProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReviewsProduct(\App\Entity\ReviewsProduct $reviewsProduct): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReviewsProduct', [$reviewsProduct]);

        return parent::removeReviewsProduct($reviewsProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantity(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantity', []);

        return parent::getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantity(int $quantity): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantity', [$quantity]);

        return parent::setQuantity($quantity);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getTags(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTags', []);

        return parent::getTags();
    }

    /**
     * {@inheritDoc}
     */
    public function setTags(?string $tags): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTags', [$tags]);

        return parent::setTags($tags);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug(string $slug): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

}
